# Generated by Django 2.1.7 on 2019-03-10 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.SmallIntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='Time Sat')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTables.ActiveTables')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tables', models.IntegerField(default=0)),
                ('tips', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='activetables',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTables.Server'),
        ),
    ]
