# Generated by Django 2.1.7 on 2019-03-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('units', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('price_per_unit', models.FloatField(default=0)),
                ('date_purchased', models.DateField()),
            ],
        ),
    ]
